In [4]:
list=[1,4,3,2,"asd",123,-5,1.5]
print(list)

[1, 4, 3, 2, 'asd', 123, -5, 1.5]


In [3]:
!pip install numpy

In [2]:
import numpy as np

In [5]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [7]:
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [8]:
c=np.array([1,2,3])
d=np.array([4,5,6])

In [9]:
print(c+d)

[5 7 9]


In [10]:
print(c-d)

[-3 -3 -3]


In [11]:
print(c*d)

[ 4 10 18]


In [12]:
print(c/d)

[0.25 0.4  0.5 ]


In [13]:
np.__version__

'1.23.5'

In [14]:
a= np.array( [ [1,2,3] , [4,5,6] ] )
print(a)

[[1 2 3]
 [4 5 6]]


In [18]:
b= np.array( [[ [1,2,3] , [4,5,6] ],[ [7,8,9] , [10,11,12] ]] )
print(b)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [32]:
print(b.std())

3.452052529534663


In [43]:
a=np.array([[1,2,3,4,6,5,6,1],[1,1,2,3,4,6,5,6]])
print(a)

[[1 2 3 4 6 5 6 1]
 [1 1 2 3 4 6 5 6]]


In [50]:
b = a.reshape((4,4))
print(b)
c = a.transpose()
print(c)

[[1 2 3 4]
 [6 5 6 1]
 [1 1 2 3]
 [4 6 5 6]]
[[1 1]
 [2 1]
 [3 2]
 [4 3]
 [6 4]
 [5 6]
 [6 5]
 [1 6]]


In [52]:
dizi1=np.array([[1],[2],[3]])
print(dizi1)

[[1]
 [2]
 [3]]


In [54]:
dizi2=np.array([1,2,3])
print(dizi2)

[1 2 3]


In [57]:
print(dizi2[2])

3


In [60]:
dizi3= np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(dizi3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [63]:
print(dizi3[1,0,1])

6


In [64]:
dizi4=np.array(["ali","veli","ömer","ayşe","fatma","mustafa"])

In [67]:
print(dizi4[:3])

['ali' 'veli' 'ömer']


In [69]:
dizi5=np.array([10,50,790,90,123,23,51,3214,52])
dizi5[dizi5<100]

array([10, 50, 90, 23, 51, 52])

In [71]:
dizi5[True]

array([[  10,   50,  790,   90,  123,   23,   51, 3214,   52]])

In [72]:
dizi6=np.array([1,2,3,4])
a = dizi6 ** 2
print(a)

[ 1  4  9 16]


In [74]:
dizi7=np.array([5,8,15,20,1,3,4,25])


In [75]:
dizi8=np.arange(10,200,3)
print(dizi8)

[ 10  13  16  19  22  25  28  31  34  37  40  43  46  49  52  55  58  61
  64  67  70  73  76  79  82  85  88  91  94  97 100 103 106 109 112 115
 118 121 124 127 130 133 136 139 142 145 148 151 154 157 160 163 166 169
 172 175 178 181 184 187 190 193 196 199]


In [79]:
dizi9=np.linspace(10,1000,27)
print(dizi9)

[  10.           48.07692308   86.15384615  124.23076923  162.30769231
  200.38461538  238.46153846  276.53846154  314.61538462  352.69230769
  390.76923077  428.84615385  466.92307692  505.          543.07692308
  581.15384615  619.23076923  657.30769231  695.38461538  733.46153846
  771.53846154  809.61538462  847.69230769  885.76923077  923.84615385
  961.92307692 1000.        ]
