# Veri Madenciliği ve Mak Öğr Alg - 9 Ekim 2024
## Numpy Kütüphanesi
### Örnekleri



# kütüphanenin içeri aktarılması
pip install ____ kütüphaneAdi ___


In [1]:
!pip install numpy

In [2]:
import numpy as np

pythonListesi=[1,2,3,4,5]

numpyArray=np.array([1,2,3,4,5])

In [3]:
print(pythonListesi)
print("------------")
print(numpyArray)

[1, 2, 3, 4, 5]
------------
[1 2 3 4 5]


In [5]:
array = np.array([1,2,3,4,5])

print(array+10) # her elemana 10 ekler

print(array*2) # her elemanı 2 ile çarpar

print(array)

[11 12 13 14 15]
[ 2  4  6  8 10]
[1 2 3 4 5]


In [8]:
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])

print(array1 + array2) #iki dizi elemanlarının toplamı
print(array1 * array2) #iki dizi elemanlarının çarpımı

[5 7 9]
[ 4 10 18]


# numpy matematik fonksiyonları

In [10]:
array = np.array([1,2,3,4,5])

print(np.sum(array)) # Elemanların toplamı

print(np.mean(array)) # Elemanların ortalaması

print(np.min(array)) # Elemanların en küçük değeri

print(np.max(array)) # Elemanların en büyük değeri

print(np.std(array)) # Standart Sapma


15
3.0
1
5
1.4142135623730951


In [11]:
dereceler= np.array([0, np.pi/2, np.pi])

print(np.sin(dereceler)) # Sinus Fonksiyonu

print(np.cos(dereceler)) # Cos Fonksiyonu

[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]


In [15]:
array = np.array([1,2,3])

print(np.exp(array)) #üstel fonksiyonu

print(np.log(array)) #logarimta fonksiyonu

[ 2.71828183  7.3890561  20.08553692]
[0.         0.69314718 1.09861229]


# numpy dizi şekillendirme ve indeksleme

In [22]:
array = np.arange(10)

print(array)
print("--------------")

#reShape
yenidenSekillendirme = array.reshape(5,2)

print(yenidenSekillendirme)

[0 1 2 3 4 5 6 7 8 9]
--------------
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


Arange komutu ile **10** elemanlı **tek satırlı** bir dizi oluşturduk

Daha sonra bu dizi **reShape** ile yeniden şekillendirdik ve **5 satır 2 sutun** seklinde gösterdik

In [29]:
array=np.arange(40)
print(array)

reshape=array.reshape(8,5)
print(reshape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]]


In [30]:
array2D = np.array( [ [1,2,3] , [4,5,6] , [7,8,9] ] )
print(array2D)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


3x3 lük matristen 6 sayısına erişmek istediğimde (**indeksleme**) satır ve sutun bilgisi girmem gerekir. NOT: sayılar 0'dan başlar 3x3 matris de 3. satır yoktur. Satırlar 0. 1. ve 2. olarak gider.

In [35]:
print(array2D[1,2])

6


In [36]:
array2D = np.array ( [ [1,2],[3,4],[5,6],[7,8]] )
print(array2D)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [37]:
print(array2D[2,1])

6


# Numpy ile Rastgele Veri Seti Oluşturma
## Basit veriseti oluşturma işlemlerinde numpy den yararlanılır.

### Örnek: Veritabanı dersinde sizlere tablolar hazırlamak için bu yöntemler kullanılmıştır.

In [40]:
rastgele_sayilar = np.random.randint(1,1001) # 1 ile 1001 arasında rastgele 1 adet sayı verir.

print(rastgele_sayilar)

885


In [44]:
sehirler = ['Konya','İstanbul','Ankara','İzmir','Giresun','Trabzon','Samsun','Rize','Ordu']

rastgele_sehir = np.random.choice(sehirler) # sehirler listesinden rastgele bir adet şehir seçer

print(rastgele_sehir)

Konya


In [46]:
isimler = ['Süleyman','Ali','Veli','Ahmet','Mehmet','Ayşe','Fatma','Hasan','Hüseyin','Mustafa','Emre','Zeynep','Elif','Ömer','İbrahim','Cihan','Selin','Burak','Mert','Ceyda','Büşra','Gökhan','Serkan','Sinan','Sude','Hakan','Eda','Derya','Can','Pınar','Eren','Aylin','Barış','Leyla','Oğuzhan','Furkan','İsmail','Melis','Dilan','Kerem','Ezgi','Kaan','Şeyma','Yusuf','Sevgi','Yasin','Damla','Gül','Cansu','Engin','Esra','Berk','Rabia']
soyisimler = ['Yılmaz','Kaya','Demir','Çelik','Şahin','Aydın','Yıldız','Öztürk','Arslan','Doğan','Koç','Kurt','Özkan','Kara','Bozkurt','Erdoğan','Gül','Polat','Aslan','Ekinci','Çetin','Kılıç','Aksoy','Acar','Çakır','Eren','Yalçın','Korkmaz','Uçar','Keskin','Bulut','Avcı','Güneş','Çınar','Erdem','Kurtuluş','Başar','Dinç','Bayraktar','Demirtaş','Altay','Şimşek','Arı','Özer','Tanrıkulu','Ersoy','Güler','Aydoğdu','Türkmen','Turan','Gündüz']
meyveler = ['Elma','Armut','Kiraz','Çilek','Portakal','Muz','Kavun','Karpuz','Üzüm','Erik','Kayısı','Şeftali','İncir','Nar','Avokado','Mandalina','Dut','Ayva','Hurma','Ananas','Vişne','Greyfurt','Böğürtlen','Yabanmersini','Kızılcık','Kivi','Limon','Papaya','Trabzon hurması','Karadut','Mango','Hindistan cevizi','Turunç','Passion fruit','Kudret narı','Ejder meyvesi','Pomelo','Liçi','Nektarin','Ahududu','Guava','Feijoa','Frambuaz','Altın çilek','Goji berry','Salatalık','Aronia','Zerdali','Mor erik','Zeytin']


In [53]:
data = {
    "Meyve" : np.random.choice(meyveler,100),
    "İsim" : np.random.choice(isimler,100),
    "Soyisim" : np.random.choice(soyisimler,100),
    "Yaş" : np.random.randint(20,101,100),
    "TCNo" : np.random.randint(10000000000,99999999999,100)
}

In [54]:
import pandas as pd

In [55]:
df = pd.DataFrame(data)

In [57]:
df

Meyve     İsim Soyisim  Yaş         TCNo
0           Kavun     Emre    Özer   44  53241056380
1       Böğürtlen    Aylin   Başar   58  77763763410
2          Karpuz   Gökhan    Eren   24  77554249896
3       Mandalina    Cihan     Gül   75  37359735065
4        Portakal     Sude   Erdem   72  97874472854
..            ...      ...     ...  ...          ...
95  Ejder meyvesi    Ahmet   Özkan   22  10483235690
96         Turunç    Melis    Kurt   60  51234283609
97            Muz  Oğuzhan     Koç   75  42738929690
98        Avokado    Leyla  Yılmaz   87  79822307395
99         Ananas    Yasin    Dinç   95  22019311007

[100 rows x 5 columns]